services:
  frontend:
    container_name: ff-frontend
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    entrypoint: node /frontend/Dockerfiles/entrypoint.js
    environment:
      - APP_PORT=80
      - APP_NAME=frontend
      - PUBLIC_URL=http://dev.food-factory.com/
    expose:
      - 80
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    networks:
      - food-factory
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`dev.food-factory.com`)

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    entrypoint: sh -c "/api/Dockerfiles/entrypoint.sh"
    environment:
      - API_ENDPOINT=http://ssh_tunnel:8080
      - APP_PORT=80
      - APP_NAME=api
      - APP_URL=http://dev.food-factory.com/api/
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`dev.food-factory.com`) && PathPrefix(`/api`)
    volumes:
      - ./api:/api
    networks:
      - food-factory

  reverse-proxy:
    container_name: ff-traefik
    image: traefik:v2.6
    command:
      - --accesslog
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - food-factory

networks:
  food-factory:
    driver: bridge

volumes:
  cache:
    driver: local
